// Starlight ships small inline <script>s (theme, sidebar, search, mobile menu)
// that the site-wide CSP in public/_headers blocks (script-src has no
// 'unsafe-inline'). After the build, hash every inline script under
// dist/docs/ and write a /docs/* rule into dist/_headers that replaces the
// site-wide CSP with the same policy plus those hashes. Pagefind search also
// needs 'wasm-unsafe-eval'.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    if (e.isDirectory()) return htmlFiles(p);
    return e.name.endsWith('.html') ? [p] : [];
  });
}

export default function docsCsp() {
  return {
    name: 'docs-csp',
    hooks: {
      'astro:build:done': ({ dir, logger }) => {
        const out = fileURLToPath(dir);
        const headersPath = join(out, '_headers');
        const headers = readFileSync(headersPath, 'utf8');

        // The site-wide policy is the first CSP line, under the /* rule.
        const base = headers.match(/^\/\*\n(?:[ \t]+.*\n)*?[ \t]+Content-Security-Policy: (.+)$/m)?.[1];
        if (!base) throw new Error('docs-csp: no site-wide Content-Security-Policy under /* in _headers');

        const hashes = new Set();
        for (const file of htmlFiles(join(out, 'docs'))) {
          for (const [, body] of readFileSync(file, 'utf8').matchAll(INLINE_SCRIPT)) {
            if (!body.trim()) continue;
            hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
          }
        }

        const policy = base.replace(
          /script-src ([^;]+)/,
          (_, sources) => `script-src ${sources} 'wasm-unsafe-eval' ${[...hashes].sort().join(' ')}`,
        );
        writeFileSync(
          headersPath,
          `${headers.trimEnd()}\n\n# Generated by src/integrations/docs-csp.mjs: Starlight inline script hashes.\n/docs/*\n  ! Content-Security-Policy\n  Content-Security-Policy: ${policy}\n`,
        );
        logger.info(`wrote /docs/* CSP with ${hashes.size} inline script hashes`);
      },
    },
  };
}
